# Generated by Django 4.2.6 on 2024-08-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Display_Flights',
            fields=[
                ('flight_number', models.IntegerField(primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
